### ISSUE TITLE
ion-refresher still active when swipping to another tab

### ISSUE THREAD

**Issue by PAFsec** [zyra/ionic2-super-tabs#136]
Hello !
First of all, thank you for your work !

I have noticed that it is possible to pull down the 'ion-refresh' while we are swipping to another tab.

If the ion-refresh isn't "visible" (ie. we are not at the top of our list in our view), then, scrolling isn't possible for the view while swipping to change tab.
If we are at the top of our list in our view, it is possible to "pull down to refresh" the list while swipping to another tab. This behavior is not pretty at all

Thank you by advance.

**Comment by ihadeed** [comment]
Thanks for reporting this. I'll look into it.

**Comment by Squiggle** [comment]
We experienced this issue, too. We implemented a fix using a shared provider, disabling the ion-refresher if there's any dragging active. Note that there's a hacky work-around we needed to implement due to a race condition.
- There is a minimum amount of movement which needs to occur before the supertabs drag is registered
- if the ion-refresher is activated in this window in time, it would start animated, then become disabled - this causes the ion-refresher into an invalid state, which causes it to freeze.

Our solution to this was:

template:
```
<ion-refresher `[enabled]="enableRefresher"`> ... </ion-refresher>
```
 
component (snippet)
```
  @ViewChild(Refresher)
  public refresher: Refresher;

  ngOnInit(): void {
    // tabsUpdateProvider is our own shared provider which exposes an
    // Observable<void> via tabsDragged. Each time this is called, you need to explicitly
    // cancel any refreshing action to avoid a race condition
    this.tabsDraggedSubscription = this.tabsUpdateProvider.tabsDragged()
    .subscribe((dragging) => {
      this.refresher.cancel();
      this.enableRefresher = !dragging;
    });
  }
```

We also forked the repo to implement the onDragStart and onDragStop events. They're a bit hacky, but @ihadeed feel free to take a [look and see if you want me to raise a PR](https://github.com/itsystems-ch/ionic2-super-tabs/commit/64bd1311083aebfe3836bbc713992d363e02f1a5).

Also, thanks so much for this supertabs component! It's exellent :1st_place_medal:

**Comment by lincolnthree** [comment]
I'm also having this issue. Throwing in my hand here, too. The workaround posted seems to be functional, but seems like a LOT of wiring just to solve this issue. Seems like the best solution, though. Will post again if I find a simpler way.

**Comment by lincolnthree** [comment]
To follow up, the workaround "works", but there's still some lag, and points / angles at which you can get the refresher to start moving down before it cancels. It should work "well enough", but the experience is a bit "janky". I think in order for this to work better, there needs to be some kind of communication between the components that attempt to capture a given gesture. I'm totally not knowledgeable about this, but it seems like this needs to be some kind of core Ionic feature in order to get it right. Maybe I'm just not informed enough about how gestures/events work. Just my thoughts, if they're helpful at all.

I've tried hijacking/implementing some of my own swipe/pan event handlers to try to disable the refresher at certain angles, but I think I'm getting it wrong.

**Comment by lincolnthree** [comment]
@Squiggle Did you have this issue with the refresher appearing to start, then cancelling in your UI implementation? I tried the enabled=false method, but I'm still seeing latency and the refresher opening some.

**Comment by Unkn0wn0x** [comment]
I've found another, very simple solution to handle this unwanted behaviour.

Listen to the `(ionPull)` output event on the `ion-refresher` and create a simple function which checks, if the `getBoundingClientRect().left` of the content is not 0. If the current `left` is not 0, it will cancel the refresher immediatly. The content will jump back to the top and no more pulling is possible for the current "refresher-pull".

For example:

```
<ion-refresher (ionRefresh)="pullToRefresh($event)" (ionPull)="checkPullToRefresh($event)">
  <!-- Your refresher content here -->
</ion-refresher>
```
* https://ionicframework.com/docs/api/components/refresher/Refresher/

```
protected checkPullToRefresh(refresher: any): void {
   if (this.content.getContentDimensions().contentLeft !== 0) return refresher.cancel();
}
```
* https://ionicframework.com/docs/api/components/content/Content/

It will never be the case, that the refresher stucks somewhere while pulling the content or the refresher stucks at a disabled state.

But You need to evaluate whether the behavior with the short jump is okay for you.

Maybe it helps someone here.

**Comment by lincolnthree** [comment]
Hey @ihadeed - Just checking. Is this fixed in 4.2.0? Thanks!
