### ISSUE TITLE
`scrollTabs` issue in latest ionic 3.2.0 release

### ISSUE THREAD

**Issue by mumairofficial** [zyra/ionic2-super-tabs#49]
I have updated my application to latest ionic release which is **3.2.0** with **angular version 4.1.0**

before that everything was working fine but,

 now I started facing a problem specially when I add `scrollTabs` attribute to `<super-tabs scrollTabs>`

**Error**
> Uncaught TypeError: Cannot read property 'nativeElement' of undefined
> 
![image](https://cloud.githubusercontent.com/assets/6498132/25948894/115bbad6-366f-11e7-8d4b-26d39f61c6d4.png)

Here is good code:
```ts
<super-tabs>
    <super-tab [root]="page1" title="First page"></super-tab>
    <super-tab [root]="page2" title="Second page"></super-tab>
    ...
  </super-tabs>
```

Broken Code with `scrollTabs`:
```ts
<super-tabs scrollTabs>
    <super-tab [root]="page1" title="First page"></super-tab>
    <super-tab [root]="page2" title="Second page"></super-tab>
    ...
  </super-tabs>
```

**Comment by mforloni** [comment]
I have the same problem. The scrollTabs (<super-tabs scrollTabs="true">) not work in this new version.

**Comment by darron1217** [comment]
I found the code change from Ionic 3.2.0 release.
https://github.com/driftyco/ionic/commit/5d562166fcc648dd42b6e7415b2f267e8f7ac141#diff-c7183d7ba6fabfec3a2be33bf4b070f8

This problem is caused by the change of `src/components/segment/segment-button.ts` file.
The code
```typescript
constructor(private _renderer: Renderer, private _elementRef: ElementRef) {}
```
Changed to
```typescript
constructor() {}
```
So now super-tabs cannot retrieve `_elementRef` from SegmentButton
```typescript
  private indexSegmentButtonWidths() {
    let index = [], total = 0;

    this.segmentButtons.forEach((btn: SegmentButton, i: number) => {
      // Cannot read property 'nativeElement' of undefined 
      index[i] = <ElementRef>(<any>btn)._elementRef.nativeElement.offsetWidth;
      total += index[i] + 10;
    });

    this.segmentButtonWidths = index;
    this.segmentWidth = total;
  }
```

So.. @ihadeed  we should figure out the way to get `_elementRef` by fixing the code below.
```typescript
@ViewChildren(SegmentButton)
private segmentButtons: QueryList<SegmentButton>;
```

**Comment by squallliu** [comment]
@ViewChildren(SegmentButton, { read: ElementRef })
private segmentButtons: QueryList<ElementRef>;

this.segmentButtons.forEach((btn: ElementRef, i: number) => {
      index[i] = btn.nativeElement.offsetWidth;
      total += index[i] + 10;
});

**Comment by ihadeed** [comment]
Working on a fix now. Getting rid of `ion-segment` completely and building a custom component from scratch. A step closer to having this plugin less "hacky" ...

**Comment by ihadeed** [comment]
Fixed in `ionic2-super-tabs@2.6.0`.

**Comment by hayuki** [comment]
@ihadeed Cannot update to 2.6.0, getting the following error: 
```
pm ERR! notarget No compatible version found: ionic2-super-tabs@2.6.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 0.2.0, 1.0.0, 1.1.0, 1.1.1, 2.0.0-alpha.1, 2.0.0-alpha.2, 2.0.0-beta.1, 2.0.0, 2.1.0, 2.2.0, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.2
npm ERR! notarget
```
Could you perhaps have forgotten to publish the new tag on npm?..

**Comment by ihadeed** [comment]
@hayuki looks like a valid tag to me... try clearing your NPM cache by running `npm cache clear`

![image](https://cloud.githubusercontent.com/assets/13794420/26244639/84eb8720-3c5e-11e7-8090-4b95fbd7b5b0.png)

![image](https://cloud.githubusercontent.com/assets/13794420/26244652/98f76d92-3c5e-11e7-8f47-0b1287f5191a.png)

**Comment by mumairofficial** [comment]
@ihadeed I have tried to install **2.6.0** it seems like installed but after clearing `npm cache`.
I checked the version which is same as before; also problem persist:
![image](https://cloud.githubusercontent.com/assets/6498132/26245362/2ec35cc0-3cad-11e7-826f-fff8537b3bc9.png)

**Comment by mumairofficial** [comment]
@ihadeed It is fixed basically version was not updated in my **package.json** which is **2.6.1** not **2.6.0**
so ionic embed older code in packaging.

DON'T forget to add **--save** flag while updating 
```sh
npm install --save ionic2-super-tabs@latest
```
