### ISSUE TITLE
ion-slide inside tabs do not work

### ISSUE THREAD

**Issue by justiceo** [zyra/ionic2-super-tabs#8]
When there is an ion-slide inside the ion-content of a swipeable tab, it wouldn't slide. 
Apparently only the root slide captures the swipe event.  

Here is an image of a sample use case for horizontal ion-slide inside ion-content:

![horizontal-slide](https://cloud.githubusercontent.com/assets/7328691/24707888/45c9a2f4-19e3-11e7-880f-f423fa6e85d2.PNG)

**Comment by ihadeed** [comment]
Thanks for reporting this. I will experiment with something similar to this and try to find a solution.

**Comment by justiceo** [comment]
horizontal ion-scroll doesn't work either

**Comment by ihadeed** [comment]
@justiceo 

I tried reproducing this while working on V2 with no luck. Not sure if I did something that fixed it or I'm just  unable to reproduce the issue.

I put the following code in one of the child pages (one of the tabs):
```html
  <ion-slides slidesPerView="5">
    <ion-slide>
      <span class="color blue"></span>
    </ion-slide>
    <ion-slide>
      <span class="color red"></span>
    </ion-slide>
    <ion-slide>
      <span class="color yellow"></span>
    </ion-slide>
    <ion-slide>
      <span class="color blue"></span>
    </ion-slide>
    <ion-slide>
      <span class="color red"></span>
    </ion-slide>
    <ion-slide>
      <span class="color yellow"></span>
    </ion-slide>
    <ion-slide>
      <span class="color blue"></span>
    </ion-slide>
    <ion-slide>
      <span class="color red"></span>
    </ion-slide>
    <ion-slide>
      <span class="color yellow"></span>
    </ion-slide>
  </ion-slides>
```
```css
ion-slides {
    height: 80px;

    ion-slide span.color {

      display: block;
      height: 50px;
      width: 50px;

      max-width: 100%;
      border-radius: 500rem;

      &.blue {
        background: blue;
      }

      &.red {
        background: red;
      }

      &.yellow {
        background: yellow;
      }

    }
  }
```

I tested this on the browser and on an Android device. Didn't experience any unexpected behaviour. I will try `ion-scroll` too in a bit.

**Comment by justiceo** [comment]
@ihadeed sorry I didn't notice you responded to this earlier. 
I pushed an example code to https://github.com/justiceo/super-tabs-example
The last two commits demonstrate the issues with ion-slide and ion-scroll.
And this is using the previous release of super-tabs, so yes it's possible that these problems have been fixed by now.

**Comment by ihadeed** [comment]
@justiceo could you please test it with the new version and let me know if you're still experiencing issues?

**Comment by justiceo** [comment]
I just did and everything worked perfectly for both ion-slide and ion-scroll! Great work and thanks!

**Comment by ihadeed** [comment]
Thanks for the update @justiceo !

**Comment by Chethannp** [comment]
@justiceo - Can you please share your code, I am still not able to use ion-scroll inside supertabs!
